# Generated by Django 3.2.3 on 2021-05-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('originLat', models.FloatField(blank=True, default=None, null=True)),
                ('originLong', models.FloatField(blank=True, default=None, null=True)),
                ('destination', models.CharField(max_length=200)),
                ('destinationLat', models.FloatField(blank=True, default=None, null=True)),
                ('destinationLong', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=200)),
                ('delivery_hub', models.CharField(max_length=200)),
                ('deliverylat', models.FloatField(blank=True, default=None, null=True)),
                ('deliverylong', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distanceCityLink', models.FloatField(blank=True, default=None, null=True)),
                ('distancePosLaju', models.FloatField(blank=True, default=None, null=True)),
                ('distanceGdex', models.FloatField(blank=True, default=None, null=True)),
                ('distanceJnT', models.FloatField(blank=True, default=None, null=True)),
                ('distanceDHL', models.FloatField(blank=True, default=None, null=True)),
                ('shortestDistance', models.CharField(default='', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_name', to='delivery.customer')),
            ],
        ),
    ]
