# Generated by Django 3.2.3 on 2021-05-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='distanceShortest',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
